[package]
name = "lisp-roots"
version = "0.1.0"
edition = "2021"

[features]
default = ["cli"]
cli = ["dep:rustyline"]

[dependencies]
rustyline = { version = "11.0.0", optional = true }

[workspace]
members = ["wasm"]
